name: PHP Coding Standards

on:
  push:
    branches: [ trunk, develop ]
  pull_request:
    branches: [ trunk, develop ]

jobs:
  build:
    strategy:
      matrix:
        php: [ 8.2 ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup proper PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer run-script packages-install

      - name: Run PHP_CodeSniffer
        run: composer run-script lint:php
        continue-on-error: true

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://avatars.githubusercontent.com/u/73898108?s=48&v=4
          SLACK_MESSAGE: "PR by ${{ github.actor }} was a ${{ job.status }}"
          SLACK_TITLE: FSE Pilot Project PR
          SLACK_USERNAME: Codeable Vetting
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
